baseURL = 'https://pea53.com/'
locale = 'en-us'
title = 'Pea53'
theme = 'compad'

[params]
  description = "I'm Tim Pease – I ride bikes and write software"
  github = "https://github.com/TwP"
  linkedin = "https://www.linkedin.com/in/timpease/"

[markup]
  [markup.highlight]
    codeFences = true
    noClasses = true
    guessSyntax = false
    tabWidth = 2
    style = 'paraiso-light'
